modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="witheringends" 
version="${file.jarVersion}" 
displayName="Withering Ends" 
logoFile="examplemod.png" 
credits="YouTube and Stackexchange" 
authors="uDasBoot" 
description='''
Some type of mod created by uDasBoot
TBD
'''

[[dependencies.witheringends]]
    modId="forge"
    mandatory=true 
    versionRange="[36,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.witheringends]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.witheringends]]
    modId="dascore"
    mandatory=true
    versionRange=""
    ordering="NONE"
    side="BOTH"